# -*- coding: utf-8 -*-
"""Repaso para PC1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYribzj7bZs-qK16O5Fjpo8l_lnYBa18
"""

#tipo de objetos
type(2)

type("2")

type(2.5)

#conversiones de tipos
float(2)

int(2.4)

int("2")

a=5
print(5)

#Abstrayendo expresiones
pi=3.14
radio=2.2
area=pi*(radio**2)
print(area)

#para mostrar salida del programa
print("hola noemi")

#Para entrada y permite realizar lecturas
nombre=input("mi nombre es:")
apellido=input("mi apellido es:")
print(nombre)

a=str("hola noemi")
print(a)

a=int("2")
print(a)

a=int(input())

a=5
b= a%2
print(b)

b=a%2
print(b)

#if-else
numero = 10

if (numero % 2) == 0:
    print("El número es par")
else:
    print("El número es impar")

a=(a%2)==0
type(a)

a=6
b=10%2
c=a+b
if(a/c)<3:
  print("resultado es verdadero")
else:
    print("resultado es falso")

a=13
b=13+a
c=a//9
d=a//b
print(c)

#1-Calcular el área de un triángulo
base=float(input("ingrese base:"))
altura=float(input("ingrese altura:"))
c=base*(altura//2)
print(f"el resultado es:{c}")

#2-concatenacion de strings
nombre=str(input("ingresa tu nombre:"))
apellido=str(input("ingresa tu apellido:"))
c=nombre + apellido
print(f"tu nombre completo es:{c}")

#3-calculadora simple
a=float(input("ingrese primer numero:"))
b=float(input("ingrese segundo numero:"))
m=str(input("tipo de operador:"))
if m=="*":
  resultado=a*b
if m=="/":
  resultado=a/b
if m=="+":
  resultado=a+b
if m=="-":
  resultado=a-b
print(f"el resultado es:{resultado}")

#conversión de temperatura
t=float(input("ingrese la temperatura en grados celsius:"))
f= (t * 9/5) + 32
print(f"la temperatura en grados fahernheit es:{f}")

#calcular imc
estatura=float(input("ingrese estatura en metros:"))
peso=float(input("ingrese peso en kilogramos"))
imc= peso / (altura ** 2)
print(f"el imc es:{imc}")

#cuenta caracteres en un string
palabra=str(input("ingrese palabra:"))
conteo=len(palabra)
print(f"la cantidad de caracter es: {conteo}")

#reversa de un string
palabra=str(input("ingrese palabra:"))
print(f"la palabra al reves es:{(palabra)[::-1]}")

#division con resto
a=float(input("ingrese primer numero:"))
b=float(input("ingrese segundo numero:"))
cociente=a//b
resto=a%b
print(f"el cociente de a y b es:{cociente}")
print(f"el resto de a y b es:{resto}")

#verificar si un numero es par o impar
n=int(input("ingrese numero :"))
if n%2==0:
  print(" el numero es par ")
if n%2!=0:
  print(" el numero es impar ")

#calculadora de propina
monto_total = float(input("Ingresa el monto total de la factura: "))
porcentaje = float(input("Ingresa el porcentaje de propina: "))
propina = (porcentaje / 100) * monto_total
total = monto_total + propina
print(f"Monto de la propina: {propina}")
print(f"Total a pagar: {total}")

"""LISTA DE EJERCIOS:

"""

#01-Aritmética
a=float(input("ingresa primer numero entero:"))
b=float(input("ingresa segundo numero entero:"))
c=str(input("tipo de operador:"))
if c=="+":
 resultado=a+b
if c=="-":
 resultado=a-b
if c=="*":
 resultado=a*b
if c=="/":
 resultado=a/b
if c=="%":
 resultado=a%b
if c=="import math":
 resultado=math.log(a)
if c=="**":
 resultado=a**b
 print(f"el resultado es:{resultado}")

#suma
b=int(input("ingresa un numero:"))
print(type(b))
print(b)
print(b+2)

#01_aritmética
import math
a=float(input("ingrese valor de a:"))
b=float(input("ingrese valor de b:"))
suma=a+b
diferencia=a-b
producto=a*b
cociente=a/b
resto=a%b
ln_a=math.log(a)
ab=a**b
print(f"la suma de ayb es:{suma}")
print(f"la diferencia de b y a es:{diferencia}")
print(f"la producto de a y b es:{producto}")
print(f"la cociente de b y a es:{cociente}")
print(f"la resto de b y a es:{resto}")
print(f"el resultado del ln_a es:{ln_a}")
print(f"el resultado de a**b es:{ab}")

#para imprimir con la cantidad de decimal que le asignes
print("%.4f" % x)

#02_interes compuesto
a=float(input("ingrese cantidad de dinero depositado:"))
t=0.04
monto_despues_de_un_año=a+a*t
monto_despues_de_dos_años=monto_despues_de_un_año+monto_despues_de_un_año*t
monto_despues_de_tres_años=monto_despues_de_dos_años+monto_despues_de_dos_años*t
print("%.2f" % monto_despues_de_un_año)
print("%.2f" %monto_despues_de_dos_años)
print("%.2f" %monto_despues_de_tres_años)

#03_distancia entre dos puntos en el planeta tierra
import math
t1=math.radians(int(input("ingrese t1:")))
g1=math.radians(int(input("ingrese g1:")))
t2=math.radians(int(input("ingrese t2:")))
g2=math.radians(int(input("ingrese g2:")))
distancia = 6371.01*math.acos(math.sin(t1)*math.sin(t2) + math.cos(t1)*math.cos(t2)*math.cos(g1-g2))
print(distancia)

#04_indice de masa corporal
peso=float(input("ingrese peso:"))
altura=float(input("ingrese altura:"))
imc=peso/(altura*altura)
print(f"tu imc es:{imc}")

#05_suma de dígitos de un numero entero

#06-cambio
n=float(input("ingrese cantidad de dinero"))
n=n*10
a=n//10
n=n-a*10
b=n//5
n=n-b*5
c=n//2
n=n-c*2
print(f"{a} monedas de 1 sol")
print(f"{b} monedas de 0.50 centimos")
print(f"{c} monedas de 0.20 centimos")
print(f"{n} monedas de 0.10 centimos")

#07_verificar PIN
pin=int(input("ingrese PIN:"))
if pin==1234:
  print(True)
else:
  print(False)

#08_saludo

#09_calcular área
lado=float(input("ingrese lado:"))
area=lado*lado-3.14159*((lado/2)**2)/2
print(area)

#10_suma de los primeros n enteros positivos
n=int(input("ingresa numero entero: "))
suma=n*(n+1)/2
print(f"la suma es:{suma}")



"""PRACTICA 1

"""

#01_Star war
n=int(input("ingresa numero:"))
print("hace mucho tiempo en una galaxia"+ "muy, "*(n-1) +"muy lejana")

#02_formula
so=float(input("ingrese posicion inicial:"))
v=float(input("ingrese velocidad:"))
t=float(input("ingrese intervalo de tiempo:"))
s=so+v*t
print(s)

#03_hora
s=int(input("ingresa numero de segundos:"))
h=s//3600
s=s-h*3600
m=s//60
s=s-m*60
print(f"segundo:{s}")
print(f"hora:{h}")
print(f"minuto:{m}")

#02_descuento
precio=float(input("ingrese precio:"))
descuento=float(input("ingrese descuento"))
c=(precio-precio*2/100)
print(c)

#03_el cambio
cb=int(input("ingrese cantidad de billete:"))
a=cb//200
cb=cb-a*200
b=cb//100
cb=cb-b*100
c=cb//50
c=cb-c*50
d=cb//20
cb=cb-d*20
print(f"{a} billeste de 200:")
print(f"{b} billeste de 100:")
print(f"{c} billeste de 50:")
print(f"{d} billeste de 20:")
print(f"{cb} billeste de 10:")

#teoria
variable= "entrada"
print(variable[1:5])

#01_calcular área
r=float(input("ingrese lado:"))
x=(2*r)**2
pi=3.14
ac=3.14*(r**2)
print(x-3/4*ac)

a=int(input("ingresa numero de 4 citras:"))
b=(a//1000)%10
c=(a//100)%10
d=(a//10)%10
e=(a%10)
print(f"la suma de cifras es:",b+c+d+e)

x=int(input("ingresa numero de 4 cifras:"))
suma=a+b+c+d
print(f"la suma es:{suma}")

# tipos de variables
a = 5 # esta variable es de tipo int (entera)
b = 0.67 # esta variable es de tipo float (flotante)
c = False # esta variable es de tipo bool
d = "hola mundo" # esta variable es de tipo cadena

x = "Perro"
y = "Gato"
print(7*(x + " " + y+ " "))

import math
x_1 = 3
x_2 = 4
x_3 = math.sqrt(x_1**2 + x_2**2)
print(x_3)